# .github/workflows/validateBranchName.yml
# ================================================
# This workflow checks that:
# - PR branches follow the pattern 'MMKP-####'
#   (e.g., MMKP-1234, MMKP-0001)
# - It runs on all PRs except those targeting:
#   main, development, and test
# ================================================

name: Validate Branch Name

on:
  pull_request: 
    branches-ignore: 
      - main
      - development
      - test


jobs:
  # Job ID for rulesets or status checks: $branch-name-check
  branch-name-check:
    runs-on: ubuntu-latest
    env:
      RegPattern: '^MMKP-[0-9]+$' 
    steps:
      - name: Check branch name
        # This step validates that the source branch name matches the required pattern
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo " Validating branch: $BRANCH_NAME"
          echo " Regex: $RegPattern"

          if [[ ! "$BRANCH_NAME" =~ $RegPattern ]]; then
            echo " Branch name does not match required pattern: $RegPattern"
            exit 1
          fi

          echo "✅ Branch name is valid"